import type { ApplicationAuditRead, ApplicationReviewSummaryRead } from "../api/types";

export const demoAudit: ApplicationAuditRead = {
  application: {
    id: "5f2c4a50-8f75-4d38-a40f-15fd5f8f27d4",
    job_id: "77b2ac60-06b2-4f6f-9a42-9a02d2e18424",
    job: {
      id: "77b2ac60-06b2-4f6f-9a42-9a02d2e18424",
      title: "Backend Platform Engineer",
      company: "ApplyGo Demo Co.",
      company_id: null,
      company_source_text: "ApplyGo Demo Co.",
      location: "Remote",
      source_url: "https://jobs.lever.co/applygo/backend-platform-engineer",
      raw_text: "Build Python APIs with FastAPI, PostgreSQL, automation, and platform workflows.",
      remote_ok: true,
      job_type: "full-time",
      ats_type: "lever",
      salary_raw: "$95,000 - $125,000",
      created_at: "2026-06-13T16:10:00Z",
      updated_at: "2026-06-13T16:10:00Z",
    },
    state: "ApplicationCreated",
    automation_mode: "manual",
    fit_score: 86,
    confidence: "high",
    recommendation: "recommended",
    score_reasons: ["Role title is available for review.", "Relevant technical keywords were found."],
    score_risks: [],
    missing_data: [],
    red_flags: [],
    created_at: "2026-06-13T16:12:00Z",
    updated_at: "2026-06-13T16:24:00Z",
  },
  events: [
    {
      event_type: "application.created",
      actor: "system",
      to_state: "ApplicationCreated",
      payload: { automation_mode: "manual" },
      created_at: "2026-06-13T16:12:00Z",
    },
    {
      event_type: "application.scored",
      actor: "scoring",
      payload: { fit_score: 86, confidence: "high", recommendation: "recommended" },
      created_at: "2026-06-13T16:16:00Z",
    },
    {
      event_type: "policy_decision_logged",
      actor: "policy",
      payload: { decision: "allow", action_type: "send_follow_up_email" },
      created_at: "2026-06-13T16:18:00Z",
    },
    {
      event_type: "executor_attempt_logged",
      actor: "worker",
      payload: { execution_mode: "dry_run", idempotency_key: "dry-run-001" },
      created_at: "2026-06-13T16:20:00Z",
    },
    {
      event_type: "executor_result_logged",
      actor: "worker",
      payload: { status: "planned" },
      created_at: "2026-06-13T16:20:01Z",
    },
  ],
  policy_decisions: [
    {
      id: "6a7f2bd6-cd99-4892-afef-5d3a28a64a7a",
      action_type: "send_follow_up_email",
      mode: "dry_run",
      decision: "allow",
      allowed: true,
      reasons: ["Dry-run mode may plan the action but must not create side effects."],
      required_overrides: [],
      risks: [],
      created_at: "2026-06-13T16:18:00Z",
    },
  ],
  executor_actions: [
    {
      id: "bbf58d5c-2dc5-411c-bd43-0c48f0d0256b",
      action_type: "send_follow_up_email",
      execution_mode: "dry_run",
      status: "planned",
      idempotency_key: "dry-run-001",
      payload: {
        policy_decision_id: "6a7f2bd6-cd99-4892-afef-5d3a28a64a7a",
        source: "dashboard",
      },
      result: {
        action_type: "send_follow_up_email",
        execution_mode: "dry_run",
        policy_decision_id: "6a7f2bd6-cd99-4892-afef-5d3a28a64a7a",
        side_effects: false,
        planned_steps: [
          "Validate recorded policy decision.",
          "Prepare send_follow_up_email payload.",
          "Record executor result in the audit trail.",
        ],
        requires: ["recorded_policy_decision", "stable_idempotency_key"],
      },
      created_at: "2026-06-13T16:20:00Z",
      completed_at: "2026-06-13T16:20:01Z",
    },
  ],
};

export const demoReviewSummary: ApplicationReviewSummaryRead = {
  application: demoAudit.application,
  latest_policy_decision: demoAudit.policy_decisions.at(-1) ?? null,
  latest_executor_action: demoAudit.executor_actions.at(-1) ?? null,
  latest_packet_review: null,
  packet_reviews: [],
  event_count: demoAudit.events.length,
  next_states: ["Draft"],
  ready_for_policy: true,
  ready_for_dry_run: true,
  ready_for_submission: false,
};
